/// <reference types="react-native-css/types" />

// NOTE: This file should be committed with your source code. It is generated by
// react-native-css/NativeWind when Metro starts, but keeping it here makes
// TypeScript aware of className props immediately.
